import { ProductItem } from "@/types/products";

export const nout: ProductItem[] = [
  {
    id: 26,
    brand: "Apple",
    model: "iPhone 14",
    memory: "128GB",
    img: ["/nout1.png", "/nout2.png", "/nout3.png"],
    price: 87999,
    discount: 4,
    quantity: 4,
    name: "Ноутбук",
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
  },
  {
    id: 27,
    brand: "Apple",
    model: "iPhone  12 ",
    memory: "64GB",
    img: ["/nout2.png", "/nout3.png", "/nout4.png"],
    price: 47756,
    discount: 10,
    quantity: 4,
    name: "Ноутбук",
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
  },
  {
    id: 28,
    brand: "HUAWEI",
    model: "nova Y61",
    memory: "128GB",
    img: ["/nout4.png", "/nout6.png", "/nout1.png"],
    price: 14117,
    discount: 15,
    quantity: 4,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 29,
    brand: "Xiaomi",
    model: "Redmi",
    memory: "128GB",
    img: ["/nout2.png", "/nout6.png", "/nout1.png"],
    price: 87999,
    discount: 80,
    quantity: 4,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 30,
    brand: "Apple",
    model: "iPhone 14",
    memory: "128GB",
    img: ["/nout4.png", "/nout6.png", "/nout1.png"],
    price: 84999,
    discount: 4,
    quantity: 4,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 31,
    brand: "HUAWEI",
    model: "nova Y61",
    memory: "128GB",
    img: ["/nout5.png", "/nout6.png", "/nout1.png"],
    price: 14117,
    discount: 15,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 32,
    brand: "Xiaomi",
    model: "Redmi",
    memory: "128GB",
    img: ["/nout2.png", "/nout6.png", "/nout1.png"],
    price: 87999,
    discount: 80,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 33,
    brand: "Apple",
    model: "iPhone 14",
    memory: "128GB",
    img: ["/nout4.png", "/nout6.png", "/nout1.png"],
    price: 84999,
    discount: 4,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 34,
    brand: "HUAWEI",
    model: "nova Y61",
    memory: "128GB",
    img: ["/nout3.png", "/nout6.png", "/nout1.png"],
    price: 14117,
    discount: 15,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 35,
    brand: "Xiaomi",
    model: "Redmi",
    memory: "128GB",
    img: ["/nout2.png", "/nout6.png", "/nout1.png"],
    price: 87999,
    discount: 80,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 36,
    brand: "Apple",
    model: "iPhone 14",
    memory: "128GB",
    img: ["/nout3.png", "/nout6.png", "/nout1.png"],
    price: 84999,
    discount: 4,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 37,
    brand: "HUAWEI",
    model: "nova Y61",
    memory: "128GB",
    img: ["/nout4.png", "/nout6.png", "/nout1.png"],
    price: 14117,
    discount: 15,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 38,
    brand: "Xiaomi",
    model: "Redmi",
    memory: "128GB",
    img: ["/nout2.png", "/nout6.png", "/nout1.png"],
    price: 87999,
    discount: 80,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 39,
    brand: "Apple",
    model: "iPhone 14",
    memory: "128GB",
    img: ["/nout5.png", "/nout6.png", "/nout1.png"],
    price: 84999,
    discount: 4,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 40,
    brand: "Xiaomi",
    model: "Redmi",
    memory: "128GB",
    img: ["/nout5.png", "/nout6.png", "/nout1.png"],
    price: 87999,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 41,
    brand: "Apple",
    model: "iPhone 14",
    memory: "128GB",
    img: ["/nout5.png", "/nout6.png", "/nout1.png"],
    price: 84999,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 42,
    brand: "Xiaomi",
    model: "Redmi",
    memory: "128GB",
    img: ["/nout5.png", "/nout6.png", "/nout1.png"],
    price: 87999,
    newModel: true,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 43,
    brand: "Apple",
    model: "iPhone 14",
    memory: "128GB",
    img: ["/nout4.png", "/nout6.png", "/nout1.png"],
    price: 84999,
    newModel: true,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 44,
    brand: "Xiaomi",
    model: "Redmi",
    memory: "128GB",
    img: ["/nout1.png", "/nout6.png", "/nout1.png"],
    price: 87999,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 45,
    brand: "Apple",
    model: "iPhone 14",
    memory: "128GB",
    img: ["/nout5.png", "/nout6.png", "/nout1.png"],
    price: 84999,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 46,
    brand: "Xiaomi",
    model: "Redmi",
    memory: "128GB",
    img: ["/nout3.png", "/nout6.png", "/nout1.png"],
    price: 87999,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 47,
    brand: "Apple",
    model: "iPhone 14",
    memory: "128GB",
    img: ["/nout6.png", "/nout6.png", "/nout1.png"],
    price: 84999,
    newModel: true,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 48,
    brand: "Xiaomi",
    model: "Redmi",
    memory: "128GB",
    img: ["/nout1.png", "/nout6.png", "/nout1.png"],
    price: 87999,
    newModel: true,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 49,
    brand: "Apple",
    model: "iPhone 14",
    memory: "128GB",
    img: ["/nout2.png", "/nout6.png", "/nout1.png"],
    price: 84999,
    discount: 4,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 50,
    brand: "Xiaomi",
    model: "Redmi",
    memory: "128GB",
    img: ["/nout4.png", "/nout3.png", "/nout1.png"],
    price: 87999,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 51,
    brand: "Apple",
    model: "iPhone 14",
    memory: "128GB",
    img: ["/nout2.png", "/nout1.png", "/nout2.png"],
    price: 84999,
    newModel: true,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
]